### PR TITLE
test: use a tmp file for binaries

### PR DESCRIPTION
**Pull request by shadowtime2000**

### CODE REVIEW

**Comment by shadowtime2000** [comment]
Basically it uses a tmp file for writing the binaries in the tests instead of a folder

**Comment by shadowtime2000** [comment]
Also tests that if `output` is configured it will output it to that file.

**Comment by shadowtime2000** [comment]
@andreespirela Can you review?

**Comment by andreespirela** [comment]
LGTM. @shadowtime2000 Do you think we can add tests for files more complex than a `txt?`, like images, and stuff like that. 

Idea:
```
// HardCoded content
let image = new Uint8Array([0,1,2]);
console.log(image == Leaf.readFileSync('./a/path/to/image.png');
```
```
// get from stdout
// assertequals(stdout == "true")
```

**Review by andreespirela — APPROVED** [review]

**Pull request merged**
